project_id = "gxpmjqbxtlgkzemdyfwl"

[functions.send-confirmation-email]
enabled = true
import_map = "./functions/send-confirmation-email/deno.json"
entrypoint = "./functions/send-confirmation-email/index.ts"
verify_jwt = false
